services:
  yggdrasil:
    container_name: ygg
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /lib/modules:/lib/modules:ro
    devices:
      - /dev/net/tun:/dev/net/tun
    env_file: ./.env
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: always
    stop_grace_period: 0s
