services:
  yggdrasil:
    build:
      dockerfile: ./dockerfiles/yggdrasil
    volumes:
      - /lib/modules:/lib/modules:ro
      - ./.env:/.env:rw
      - ./configs/yggdrasil.conf:/etc/yggdrasil.conf
    devices:
      - /dev/net/tun:/dev/net/tun
    network_mode: host
    privileged: true # Done, because it is the only way to modify sysctls here
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: always
    stop_grace_period: 0s

  radvd:
    build:
      dockerfile: ./dockerfiles/radvd
    volumes:
      - ./configs/radvd.conf:/etc/radvd.conf
    network_mode: host
    cap_add:
      - NET_ADMIN
    restart: always
    stop_grace_period: 0s
