interface ${DEFAULT_DEVICE} {
	AdvSendAdvert on;
	prefix ${YGGDRASIL_SUBNET} {
		AdvOnLink on;
		AdvAutonomous on;
		AdvValidLifetime 86400;
		AdvPreferredLifetime 14400;
		AdvRouterAddr on;
	};
	route 200::/7 {
		AdvRoutePreference high;
		AdvRouteLifetime infinity;
	};
};
